version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  build:
    commands:
      - rake config:codebuild
      - rake deploy:cta:$TARGET_ENVIRONMENT
reports:
  sanity:
    files:
      - "out/reports/**/TEST-*.xml"
    file-format: "JUNITXML"
  jacoco-report:
    files:
      - "out/reports/**/jacocoTestReport.xml"
    file-format: "JACOCOXML"
artifacts:
  name: $(date +%Y%m%d%H%M%S)-deploy-cta-$TARGET_ENVIRONMENT.zip
  files:
    - "out/**/*"
  discard-paths: no
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
