version: 0.2
env:
  shell: bash
  git-credential-helper: yes
phases:
  build:
    commands:
      - rake config:codebuild
      - rake release:analytics:$TARGET_ENVIRONMENT RELEASE_VERSION=$RELEASE_VERSION      
reports:
  sanity:
    files:
      - "out/reports/**/TEST-*.xml"
    file-format: "JUNITXML"
  jacoco-report:
    files:
      - "out/reports/**/jacocoTestReport.xml"
    file-format: "JACOCOXML"
artifacts:
  name: $(date +%Y%m%d%H%M%S)-release-analytics-$TARGET_ENVIRONMENT.zip
  files:
    - "out/**/*"
  discard-paths: no
